### ISSUE TITLE
Patches are aging, can these be refreshed to situation at head ?

### ISSUE THREAD

**Issue by hzeller** [antmicro/surelog-uhdm-ibex-guide#5]
While we're still working on getting the necessary changes in Yosys upstream, we should keep a patch here that cleanly applies to close to head of Yosys.

**Comment by hzeller** [comment]
Can't assign issues in thie repo, so doing it the manual mention-way @kgugala  :)

**Comment by hzeller** [comment]
Any updates here ?

**Comment by kgugala** [comment]
yep, this branch holds updated patches/readme https://github.com/antmicro/surelog-uhdm-ibex-guide/tree/psagan/bump
Need to test it and we're ready to merge

**Comment by hzeller** [comment]
and, ready to merge ?

**Comment by tgorochowik** [comment]
Unfortunately the design does not work on hardware when synthesizing with latest yosys, we are still debugging this. We should have more details soon.
